matrix:
  include:
    - os: linux
      sudo: required
services:
  - docker
install:
  - docker build -t swift .
script:
  # Workaround: Use root instead of developer.
  # - docker run -u developer -v $TRAVIS_BUILD_DIR:/mnt/project swift swift test -C /mnt/project
  - docker run -v $TRAVIS_BUILD_DIR:/mnt/project swift swift test -C /mnt/project
